#!/usr/bin/env bash
# Generate deterministic Annex-B fixtures + synthetic test PKI for verify tests.
# Signed streams are produced with tests/tools/oms_sign_annexb (official ONVIF C API),
# not with a Nanexus sign product command.
#
# oms_sign_annexb enables emulation-prevention bytes on generated SEIs so Annex-B
# parsers do not split signature/TLV payloads on false start codes (upstream
# default sei_epb is false).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-${ROOT}/tests/fixtures/generated}"
SIGN_BIN="${OMS_SIGN_ANNEXB:-}"
FFMPEG="${FFMPEG:-ffmpeg}"

mkdir -p "${OUT}/pki" "${OUT}/h264" "${OUT}/h265"

# --- synthetic test-only PKI (not for production) ---
if [[ ! -f "${OUT}/pki/ca.pem" ]]; then
  openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
    -keyout "${OUT}/pki/ca.key.pem" \
    -out "${OUT}/pki/ca.pem" \
    -subj "/CN=Nanexus Test CA" >/dev/null 2>&1
  openssl req -newkey rsa:2048 -nodes \
    -keyout "${OUT}/pki/signer.key.pem" \
    -out "${OUT}/pki/signer.csr.pem" \
    -subj "/CN=Nanexus Test Signer" >/dev/null 2>&1
  openssl x509 -req -in "${OUT}/pki/signer.csr.pem" -CA "${OUT}/pki/ca.pem" \
    -CAkey "${OUT}/pki/ca.key.pem" -CAcreateserial -out "${OUT}/pki/signer.cert.pem" \
    -days 3650 -sha256 >/dev/null 2>&1
  cat "${OUT}/pki/signer.cert.pem" "${OUT}/pki/ca.pem" > "${OUT}/pki/signer-chain.pem"
fi

# Tiny synthetic video → Annex-B
"${FFMPEG}" -y -hide_banner -loglevel error -f lavfi -i "color=c=black:s=64x64:d=1" \
  -c:v libx264 -pix_fmt yuv420p -g 15 -bf 0 -an -f h264 "${OUT}/h264/unsigned.h264"
"${FFMPEG}" -y -hide_banner -loglevel error -f lavfi -i "color=c=black:s=64x64:d=1" \
  -c:v libx265 -pix_fmt yuv420p -g 15 -an -f hevc "${OUT}/h265/unsigned.h265"

if [[ -z "${SIGN_BIN}" ]]; then
  echo "NOTE: set OMS_SIGN_ANNEXB to oms_sign_annexb binary to generate signed fixtures"
  exit 0
fi

"${SIGN_BIN}" h264 "${OUT}/pki/signer.key.pem" "${OUT}/pki/signer-chain.pem" \
  "${OUT}/h264/unsigned.h264" "${OUT}/h264/signed.h264"
"${SIGN_BIN}" h265 "${OUT}/pki/signer.key.pem" "${OUT}/pki/signer-chain.pem" \
  "${OUT}/h265/unsigned.h265" "${OUT}/h265/signed.h265"

# Deterministic one-byte corruption after first start code + header byte.
python3 - <<PY
from pathlib import Path
src = Path("${OUT}/h264/signed.h264")
dst = Path("${OUT}/h264/tampered.h264")
data = bytearray(src.read_bytes())
# Flip a payload byte well after a 4-byte start code.
idx = data.find(b"\x00\x00\x00\x01")
if idx < 0:
    raise SystemExit("no start code")
# search for a VCL-like NAL (type 1 or 5 in low 5 bits) and flip later byte
pos = 0
flipped = False
while True:
    i = data.find(b"\x00\x00\x00\x01", pos)
    if i < 0:
        i = data.find(b"\x00\x00\x01", pos)
        sc = 3 if i >= 0 else -1
    else:
        sc = 4
    if i < 0:
        break
    nal_hdr = data[i + sc]
    nal_type = nal_hdr & 0x1F
    if nal_type in (1, 5) and i + sc + 8 < len(data):
        data[i + sc + 4] ^= 0xFF
        flipped = True
        break
    pos = i + sc + 1
if not flipped:
    raise SystemExit("no VCL NAL found to corrupt")
dst.write_bytes(data)
print("wrote", dst)
PY

cat > "${OUT}/README.md" <<'EOF'
# Generated verify fixtures

Synthetic Annex-B streams and test-only PKI for Nanexus verify tests.

* Generated by `scripts/gen-verify-fixtures.sh`
* Unsigned media: ffmpeg lavfi color bars / black frames
* Signed media: official ONVIF C API via `oms_sign_annexb` (not Nanexus sign)
* Keys: ephemeral OpenSSL test CA/signer — not production material

Do not treat these keys or results as real device identity evidence.
EOF

echo "PASS: fixtures at ${OUT}"
